export const size = {
  huge: 50,
  xxxtitle: 38,
  xxtitle: 36,
  xtitle: 34,
  title: 32,
  h1: 30,
  h2: 28,
  h3: 26,
  h4: 25,
  h5: 24,
  h6: 22,
  xxlarge: 20,
  xlarge: 19,
  large: 18,
  medium: 17,
  normal: 16,
  small: 15,
  xsmall: 14,
  xxsmall: 13,
  tiny: 12,
  xtiny: 11,
  xxtiny: 10,
  xxxtiny: 9,
};
export const family = {
  Roboto_Regular: 'Roboto-Regular',
  Roboto_Medium: 'Roboto-Medium',
  Roboto_Bold: 'Roboto-Bold',
  Roboto_Italic: 'Roboto-Italic',
  Roboto_BoldItalic: 'Roboto-BoldItalic',
  Roboto_Black: 'Roboto-Black',
  Roboto_BlackItalic: 'Roboto-BlackItalic',
  Roboto_Thin: 'Roboto-Thin',
  Roboto_ThinItalic: 'PRoboto-ThinItalic',
  Roboto_LightItalic: 'Roboto-LightItalic',
  Roboto_Light: 'Roboto-Light',
  Roboto_MediumItalic: 'Roboto-MediumItalic',
};
